name: Sync README
on:
  push:
    paths:
      - 'README.MD'

jobs:
  sycn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup GIT
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@koitech.com'

      - name: Copy Readme to Servidor
        run: |
          git clone "https://${{ secrets.PAT_DISPATCH }}@github.com/KoiTech-Aero/Servidor.git"
          cp README.md ./Servidor/README.md
          cd ./Servidor
          git add README.md
          git commit -m "docs: Atualiza README"
          git push

      - name: Copy Readme to FrontEnd
        run: |
          git clone "https://${{ secrets.PAT_DISPATCH }}@github.com/KoiTech-Aero/FrontEnd.git"
          cp README.md ./FrontEnd/README.md
          cd ./FrontEnd
          git add README.md
          git commit -m "docs: Atualiza README"
          git push